server:
  port: 8081

spring:
  application:
    name: Eureka-Server

eureka:
  instance:
    hostname: 192.168.9.214
  client:
    serviceUrl:
      defaultZone: http://192.168.9.10:8080/eureka/
  server:
    enable-self-preservation: false