server:
  port: 8080

spring:
  application:
    name: Eureka-Server

eureka:
  instance:
    hostname: 192.168.9.10
  client:
    serviceUrl:
      defaultZone: http://192.168.9.214:8081/eureka/
  server:
    enable-self-preservation: false


