#server:
#  port: 8080
#
#
#
#eureka:
#  instance:
#    hostname: 192.168.9.10
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  server:
#    enable-self-preservation: false
#
